// Generated by CoffeeScript 1.3.1

/**
共有
*/


(function() {
  var SocialSupport;

  module.exports = SocialSupport = (function() {
    var V, _callLineText, _openIntent,
      _this = this;

    SocialSupport.name = 'SocialSupport';

    V = 1.1;

    SocialSupport.LINE = 0;

    SocialSupport.TWITTER = 1;

    SocialSupport.FACEBOOK = 2;

    SocialSupport.SINAWEIBO = 3;

    function SocialSupport() {}

    _openIntent = function(sendstring, image) {
      var intent;
      intent = Ti.Android.createIntent({
        action: Ti.Android.ACTION_SEND,
        type: 'text/plain'
      });
      intent.putExtra(Ti.Android.EXTRA_TEXT, sendstring);
      return Ti.Android.currentActivity.startActivity(Ti.Android.createIntentChooser(intent, L("whichApplication", "which application")));
    };

    _callLineText = function(linestr) {
      var openstr;
      linestr = encodeURIComponent(linestr);
      openstr = "line://msg/text/" + linestr;
      if (Ti.UI.iOS != null) {
        if (Ti.Platform.canOpenURL(openstr)) {
          return Ti.Platform.openURL(openstr);
        } else {
          return Ti.Platform.openURL("http://line.naver.jp/R/msg/text/?" + linestr);
        }
      } else {
        return Ti.Platform.openURL(openstr);
      }
    };

    SocialSupport.openShare = function(num, text, image) {
      var alertmessage, sns_obj, _Social;
      if (num == null) {
        num = 0;
      }
      if (text == null) {
        text = "";
      }
      if (Ti.UI.iOS != null) {
        _Social = require("dk.napp.social");
        sns_obj = {
          text: text
        };
        if (image != null) {
          sns_obj.image = image;
        }
        alertmessage = L("serviceNotProvisioned", "Servic No Provisioned");
        switch (num) {
          case SocialSupport.TWITTER:
            if (_Social.isTwitterSupported()) {
              return _Social.twitter(sns_obj);
            } else {
              return alert("Twitter:" + alertmessage);
            }
        }
      }
    };

    SocialSupport.postDialogShow = function(text, url, image, line) {
      var FACEBOOK, LINE, OTHER, SINAWEIBO, TWITTER, cancelnum, dialog, options, sendstring, _Social;
      if (text == null) {
        text = "";
      }
      if (line == null) {
        line = true;
      }
      if (Ti.UI.iOS != null) {
        _Social = require("dk.napp.social");
        LINE = 0;
        TWITTER = 1;
        FACEBOOK = 2;
        SINAWEIBO = 3;
        options = [];
        options[LINE] = "LINE";
        options[TWITTER] = "Twitter";
        options[FACEBOOK] = "Facebook";
        options[SINAWEIBO] = L("SinaWeibo", "SinaWeibo");
        options.push(L("cancel", "cancel"));
        cancelnum = options.length - 1;
        dialog = Ti.UI.createOptionDialog({
          cancel: cancelnum,
          options: options,
          title: L("choose_account_label", "choose account label"),
          message: L("choose_account_label", "choose account label")
        });
        dialog.addEventListener("click", function(e) {
          var alertmessage, e_index, sns_obj;
          e_index = e.index;
          if (e_index === cancelnum) {
            return;
          }
          sns_obj = {
            text: text
          };
          if (url != null) {
            sns_obj.url = url;
          }
          if (image != null) {
            sns_obj.image = image;
          }
          alertmessage = L("serviceNotProvisioned", "Servic No Provisioned");
          switch (e_index) {
            case LINE:
              return _callLineText(text);
            case TWITTER:
              if (_Social.isTwitterSupported()) {
                return _Social.twitter(sns_obj);
              } else {
                return alert("Twitter:" + alertmessage);
              }
              break;
            case FACEBOOK:
              if (_Social.isFacebookSupported()) {
                return _Social.facebook(sns_obj);
              } else {
                return alert("Facebook:" + alertmessage);
              }
              break;
            case SINAWEIBO:
              if (_Social.isSinaWeiboSupported()) {
                return _Social.sinaweibo(sns_obj);
              } else {
                return alert("" + options[SINAWEIBO] + ":" + alertmessage);
              }
          }
        });
        return dialog.show();
      } else if (Ti.Android != null) {
        LINE = 0;
        OTHER = 1;
        sendstring = "" + text + " " + url;
        if (line) {
          dialog = Ti.UI.createOptionDialog({
            options: ["LINE", L("more_item_label", "other"), L("cancel")],
            cancel: 1,
            title: L("choose_account_label", "account")
          });
          dialog.addEventListener('click', function(e) {
            var e_index;
            e_index = e.index;
            switch (e_index) {
              case LINE:
                return _callLineText(sendstring);
              case OTHER:
                return _openIntent(sendstring);
            }
          });
          return dialog.show();
        } else {
          return _openIntent(sendstring);
        }
      }
    };

    return SocialSupport;

  }).call(this);

}).call(this);
